#!/usr/bin/env python3
"""
Script Generator — Job Automation Studio
Reads user preferences → outputs a personalised Python automation script.
"""

import json
from pathlib import Path

TEMPLATE_DIR = Path(__file__).parent.parent / "TEMPLATES"


def generate_script(config: dict) -> str:
    """
    Generate a complete Python automation script from a config dict.

    config keys:
      name, email, phone, role, locations[], sites[],
      exclusions[], daily_cap, salary_local, salary_remote,
      skip_senior, remote_only, tone, work_type,
      cv_skills[], ai_mode, tool
    """
    locs_json  = json.dumps(config.get("locations", []), indent=2)
    sites_json = json.dumps(config.get("sites", []), indent=2)
    excl_json  = json.dumps(config.get("exclusions", []), indent=2)
    skills     = ", ".join(config.get("cv_skills", [])[:8])

    tone_open  = {
        "Professional": "I am writing to express my strong interest in",
        "Friendly":     "I'm really excited about the opportunity to join",
        "Direct":       "I want to apply for",
    }
    tone_close = {
        "Professional": "Thank you for your time and consideration.",
        "Friendly":     "Can't wait to hear from you!",
        "Direct":        "Looking forward to your response.",
    }
    to = tone_open.get(config.get("tone", "Professional"), tone_open["Professional"])
    tc = tone_close.get(config.get("tone", "Professional"), tone_close["Professional"])

    return f'''#!/usr/bin/env python3
"""
Job Application Automation Script
Generated by Job Automation Studio
Candidate: {config.get("name", "Your Name")}
Role: {config.get("role", "Target Role")}

⚠️  For best results, run with an AI agent (QClaw, OpenClaw, Claude).
    The AI handles anti-bot detection, form filling, and error recovery.
"""

import json, time, random
from pathlib import Path

# ── CONFIG ─────────────────────────────────────────────────────────────────────
CANDIDATE_NAME  = "{config.get("name", "Your Name")}"
EMAIL           = "{config.get("email", "your@email.com")}"
PHONE           = "{config.get("phone", "+62 xxx xxxx xxxx")}"
TARGET_ROLE     = "{config.get("role", "Target Role")}"
WORK_TYPE       = "{config.get("work_type", "Remote")}"
COVER_TONE      = "{config.get("tone", "Professional")}"
DAILY_CAP       = {config.get("daily_cap", 50)}

LOCATIONS       = {locs_json}
JOB_SITES       = {sites_json}
EXCLUDE         = {excl_json}
SKIP_SENIOR     = {str(config.get("skip_senior", True)).title()}
REMOTE_ONLY     = {str(config.get("remote_only", False)).title()}
SALARY_LOCAL    = "{config.get("salary_local", "negotiable")}"
SALARY_REMOTE   = "{config.get("salary_remote", "negotiable")}"

# ── TRACKER ─────────────────────────────────────────────────────────────────────
DATA_DIR = Path(__file__).parent / "data"
TRACKER  = DATA_DIR / "applied_ids.json"
DATA_DIR.mkdir(parents=True, exist_ok=True)

def load_ids():
    if TRACKER.exists():
        return set(json.loads(TRACKER.read_text()).get("applied_ids", []))
    return set()

def save_ids(ids):
    TRACKER.write_text(json.dumps({{"applied_ids": list(ids)}}, indent=2))

# ── FILTERS ─────────────────────────────────────────────────────────────────────
BANKING = [
    "bank","bca","bni","bri","mandiri","cimb","maybank","ocbc","uob","dbs",
    "permata","panin","btn","jago","ovo","dana","gopay","linkaja","shopeepay",
    "fintech","financial","finance","investment","securities","insurance",
] + [e.lower() for e in EXCLUDE]

SENIOR_KW = ["senior","lead","manager","director","vp","principal","supervisor","chief","head of","intern"]

def is_banking(company: str) -> bool:
    return any(b in company.lower() for b in BANKING)

def is_senior(title: str) -> bool:
    return any(k in title.lower() for k in SENIOR_KW)

def should_apply(title: str, company: str, is_remote: bool) -> bool:
    if is_senior(title) and SKIP_SENIOR:
        return False
    if is_banking(company):
        return False
    if REMOTE_ONLY and not is_remote:
        return False
    return True

# ── COVER LETTER ─────────────────────────────────────────────────────────────────
def cover_letter(role: str, company: str) -> str:
    return (
        f"Dear Hiring Manager,\\n\\n"
        f"{to} the {{role}} position at {{company}}.\\n\\n"
        f"I bring experience in {{skills}}. I'm comfortable working {{WORK_TYPE.lower()}} "
        f"and am eager to contribute to your team.\\n\\n"
        f"Salary: {{SALARY_LOCAL}} (local) / {{SALARY_REMOTE}} (remote outside Indonesia).\\n\\n"
        f"{{tc}}\\n\\nBest regards,\\n{{CANDIDATE_NAME}}\\n{{EMAIL}}"
    )

# ── SEARCH URL BUILDER ──────────────────────────────────────────────────────────
def build_url(site: str, role: str, location: str) -> str:
    re = role.replace(" ", "+")
    lo = location.replace(",", "%2C").replace(" ", "+")
    table = {{
        "LinkedIn":       f"https://www.linkedin.com/jobs/search/?keywords={{re}}&location={{lo}}&f_AL=true",
        "Indeed":         f"https://www.indeed.com/jobs?q={{re}}&l={{lo}}",
        "Glassdoor":      f"https://www.glassdoor.com/Search/results.htm?keyword={{re}}&loc={{lo}}",
        "Jobstreet ID":   f"https://www.jobstreet.co.id/id/job-search?keywords={{re}}&locations={{location}}",
        "Glints":         f"https://glints.com/lowongan-kerja/?keywords={{re}}",
        "AngelList":      f"https://angel.co/jobs?keywords={{re}}",
        "WeWorkRemotely": "https://weworkremotely.com",
        "RemoteOK":       "https://remoteok.com",
    }}
    return table.get(site, f"https://www.google.com/search?q={{re}}+jobs+{{lo}}")

# ── MAIN ─────────────────────────────────────────────────────────────────────────
def main():
    applied_ids = load_ids()
    applied_today = 0

    for site in JOB_SITES:
        if applied_today >= DAILY_CAP:
            break
        for location in LOCATIONS:
            if applied_today >= DAILY_CAP:
                break
            url = build_url(site, TARGET_ROLE, location)
            print(f"[SEARCH] {{site}} | {{TARGET_ROLE}} @ {{location}}")
            print(f"         {{url}}")
            # ── Integrate AI agent here ────────────────────────────────────
            # With QClaw/OpenClaw:
            # "Run my automation. Open: {{url}}"
            # The AI will log in, find jobs, and apply automatically.
            time.sleep(random.uniform(45, 90))  # anti-bot cooldown
            applied_today += 1

    save_ids(applied_ids | {{"new_ids_here"}})
    print(f"\\n✅ Done! Applied: {{applied_today}} today.")

if __name__ == "__main__":
    main()
'''
